// react-frontend/src/pages/Register/index.js
import React, { useState, useRef } from "react";
import { Link } from "react-router-dom";

// carrega o icone da seta para esquerda do pacote feather icons
import { FiArrowLeft } from "react-icons/fi";

// carrega a página RegisterSuccess
import RegisterSuccess from '../RegisterSuccess';

// carrega a api
import api from '../../services/api';

// importa o styles local
import './styles.css';

// carrega o logo da pasta assets
import logoImg from '../../assets/logo.svg';

// import json estados e cidades
import { estados } from '../../assets/estados-cidades.json';

export default function Register() {
  // define um state para ver se o registro obteve sucesso ou não
  const [successRegistration, setSuccessRegistration] = useState(false);
  // define um stage para ver se o email foi enviado ou não
  const [sentEmail, setSentEmail] = useState(false);

  // define os states
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [whatsapp, setWhatsapp] = useState("");
  const [city, setCity] = useState("");
  const [uf, setUf] = useState("");
  const [password, setPassword] = useState("");
  const [citiesJSON, setCitiesJSON] = useState([]);

  // instancia o btnRegister como uma referencia
  const btnRegister = useRef();
 
  // define a função handleRegister
  async function handleRegister(e) {
    // previne o funcionamento normal do envio do formulário
    e.preventDefault();

    // Desabilita o botao para que não seja enviado o formulário mais de uma vez
    btnRegister.current.setAttribute('disabled', true);

    // armazena os states dentro da variavel data
    const data = {
      name,
      email,
      whatsapp,
      city,
      uf,
      password
    };

    // bloco de declaração try, se funcionar:
    try {
      // envia os dados do formulário como metodo post para a rota 'ongs' do backend
      const response = await api.post('ongs', data);
      // verifica se o e-mail foi enviado
      if (response.data.email === true) {
        setSentEmail(true);
      }
      // define o state successRegistration como verdadeiro
      setSuccessRegistration(true);

    // se der erro
    } catch (error) {
      // define o state successRegistration como falso
      setSuccessRegistration(false);
      // envia alerta de erro ao navegador
      alert(error.response.data.message);
      // destrava o botao
      btnRegister.current.removeAttribute('disabled');
    }
  }

  function handleSelectState(uf) {
    // recebe o UF do e.target.value e define o UF
    setUf(uf);
    // filtra entre os estados do json o estado que tenha a sigla === uf
    const estadoSelecionado = estados.filter(estado => estado.sigla === uf);
    // define a cidade selecionada como o estado[0]['cidades'] para popular o select city
    setCitiesJSON(estadoSelecionado[0]['cidades']);
  }

  // se o registro foi um sucesso
  if (successRegistration) {
    // exibe este jsx com a página RegisterSuccess com um children da ong_key
    return (
      <RegisterSuccess>
        {{email, sentEmail}}
      </RegisterSuccess>
    );
    
  // se não tiver feito ainda o registro ou não foi um sucesso exiba ou mantenha este jsx
  } else {
    return (
      <div className="register-container">
        <div className="content">
          <section>
            <img src={logoImg} alt="Be The Hero" />
            <h1> Cadastro </h1> <p>Faça seu cadastro, entre na plataforma e ajude pessoas a encontrarem os casos de sua ONG. </p>
            <Link to="/" className="svg-link">
              <FiArrowLeft size={16} color="#E02041" />
              Voltar para o logon
            </Link>
          </section>
          <form onSubmit={handleRegister}>
            <input
              placeholder="Nome da ONG"
              value={name}
              required
              onChange={e => setName(e.target.value)}
            />
            <input 
              type="email" 
              placeholder="E-mail" 
              value={email} 
              required
              onChange={e => setEmail(e.target.value)}
            />
            <input 
              type="tel" 
              placeholder="Whatsapp"
              value={whatsapp} 
              required
              minLength={10}
              maxLength={11}
              onChange={e => setWhatsapp(e.target.value)}
            />
            <div className="input-group">
              <select
                value={city}
                onChange={e => setCity(e.target.value)}
                required
              >
                {citiesJSON.length > 0 ? 
                  <option hidden>Escolha uma cidade</option>
                :
                  <option hidden>Escolha um UF</option>
                }
                {citiesJSON.length > 0 ? 
                  citiesJSON.map(cidade => (
                    <option
                      key={cidade}
                      value={cidade}>{cidade}</option>
                  ))
                :
                  ''
                }
              </select>
              <select
                value={uf}
                required
                onChange={e => handleSelectState(e.target.value)}
                style={{
                  width: 130
                }}
              >
                <option hidden>UF</option>
               {estados.map(estado => (
                  <option
                    key={estado.sigla}
                    value={estado.sigla}
                  >{estado.sigla}</option>
               ))}
              </select>
            </div>
            <input
            type="password"
            value={password}
            onChange={e => setPassword(e.target.value)}
            required
            placeholder='Sua senha'
          />
            <button ref={btnRegister} className="button" type="submit">
              Cadastrar
            </button>
          </form>
        </div>
      </div>
    );
  }
}

// vue-frontend/src/pages/Register/index.vue
<template>
    <div>
        <div v-if="success" class="register-success-container">
            <div class="content">
                <section>
                    <img src="../../assets/logo.svg" alt="Be The Hero"/>
                    <h1> Cadastro realizado com sucesso! </h1>
                    <div v-if="emailEnviado">
                        <p>Seja bem vindo ao Be The Hero!! Confira seu e-mail enviamos uma confirmação:</p>
                        <a 
                            rel="noopener noreferrer"
                            target="_blank" 
                            :href="'http://'+email.split('@')[1]" 
                            style='
                            background: #fff;
                            padding: 20px;
                            text-align: center;
                            display: block;
                            margin: 10px;
                            font-size: 30px;
                            color: #1e1e1f;
                            text-decoration: none;
                            font-weight: bold;
                            '
                        >
                            Abrir o {{ email.split('@')[1].split('.')[0].charAt(0).toUpperCase() + email.split('@')[1].slice(1) }}
                        </a>
                    </div>
                    <button 
                        class="button"
                        @click="$router.push('/profile')"
                    >
                        Ver seu perfil
                    </button>
                </section>
            </div>
        </div>
        <div v-else class="register-container">
            <div class="content">
                <section>
                    <img src="../../assets/logo.svg" alt="Be The Hero"/>
                    <h1> Cadastro </h1> <p>Faça seu cadastro, entre na plataforma e ajude pessoas a encontrarem os casos de sua ONG. </p>
                    <router-link to="/" class="svg-link">
                        <arrow-left-icon size="1.5x" class="red-hero"></arrow-left-icon>
                        Voltar para o logon
                    </router-link>
                </section>
                <form autocomplete="off" v-on:submit.prevent="handleRegister">
                    <input
                    autocomplete="off"
                    placeholder="Nome da ONG"
                    v-model="name"
                    required
                    />
                    <input 
                    type="tel" 
                    autocomplete="off"
                    placeholder="Whatsapp"
                    v-model="whatsapp"
                    required
                    minLength="10"
                    maxLength="11"
                    />
                    <input 
                    type="email" 
                    autocomplete="off"
                    placeholder="E-mail" 
                    v-model="email"
                    required
                    />
                    <div class="input-group">
                        <select 
                            autocomplete="off"
                            required
                            v-model="cidadeSelecionada"
                        >
                            <option selected hidden disabled>
                                <span v-if="typeof estadoSelecionado === 'string'">Escolha um UF</span>
                                <span v-else>Escolha uma cidade</span>
                            </option>
                            <option v-for="cidade in estadoSelecionado['cidades']" :key="cidade" :value="cidade">{{ cidade }}</option>
                        </select>
                        <select 
                            autocomplete="off"
                            required
                            v-model="estadoSelecionado"
                            style="
                                width: 130px;
                                text-transform: uppercase;
                            "
                        >
                            <option selected hidden disabled>UF</option>
                            <option v-for="estado in estados" :key="estado.sigla" :value="estado">{{ estado.sigla }}</option>
                        </select>
                    </div>
                    <input
                        type="password"
                        v-model="password"
                        required
                        autocomplete="off"
                        placeholder='Sua senha'
                />
                    <button :disabled="sending" class="button" type="submit">
                    Cadastrar
                    </button>
                </form>
            </div>
        </div>
    </div>
</template>

<script>
import { ArrowLeftIcon } from 'vue-feather-icons'
import { estados } from '../../assets/estados-cidades.json'

export default {
    name: 'Register',
    components: {
        ArrowLeftIcon
    },
    data() {
        return {
            success: false,
            sending: false,
            name: '',
            email: '',
            whatsapp: '',
            city: '',
            uf: '',
            password: '',
            emailEnviado: false,
            cidadeSelecionada: 'Escolha um UF',
            estadoSelecionado: 'UF',
            estados: estados
        }
    },
    methods: {
        async handleRegister() {
            this.sending = true

            const name = this.name
            const email = this.email
            const whatsapp = this.whatsapp
            const city = this.city
            const uf = this.uf
            const password = this.password
            
            await this.axios.post('ongs', {
                name,
                email,
                whatsapp,
                city,
                uf,
                password
            })
            .then((response) => {
                this.success = true
                this.$toast.success(`Bem vinda ${name}`)

                this.$store.commit('SET_ONG_NAME', response.data.name)
                this.$store.commit('SET_EXPIRE_TIME', response.data.expire_at)
                this.$store.commit('SET_EXPIRED', false)
                this.$store.commit('USER_LOGGED', true)
                if(response.data.email === true) {
                    this.emailEnviado = true
                }
            })
            .catch((error) => {
                this.sending = false
                if (error.response.data.statusCode === 400) {
                    this.$toast.error(error.response.data.message)
                } else {
                    this.$toast.error(error.response.data.message)
                }
            })
        }
    },
    watch: {
        estadoSelecionado(val) {
            this.cidadeSelecionada = 'Escolha uma cidade'
            this.uf = val.sigla
        },
        cidadeSelecionada(val) {
            this.city = val
        }
    },
}
</script>

<style scoped>
.register-success-container {
    width: 100%;
    max-width: 1120px;
    height: 100vh;
    margin: 0 auto;

    display: flex;
    align-items: center;
    justify-content: center;
}

.register-success-container .content {
    width: 100%;
    padding: 96px;
    background: #f0f0f5;
    box-shadow: 0 0 100px rgba(0, 0 ,0, 0.1);
    border-radius: 8px;
    
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.register-success-container .content section {
    width: 100%;
}

.register-success-container .content section h1 {
    margin: 64px 0 32px;
    font-size: 32px;
}

.register-success-container .content section p {
    font-size: 18px;
    color: #737380;
    line-height: 32px;;
}

.register-container {
    width: 100%;
    max-width: 1120px;
    height: 100vh;
    margin: 0 auto;

    display: flex;
    align-items: center;
    justify-content: center;
}

.register-container .content {
    width: 100%;
    padding: 96px;
    background: #f0f0f5;
    box-shadow: 0 0 100px rgba(0, 0 ,0, 0.1);
    border-radius: 8px;
    
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.register-container .content section {
    width: 100%;
    max-width: 380px;
}

.register-container .content section h1 {
    margin: 64px 0 32px;
    font-size: 32px;
}

.register-container .content section p {
    font-size: 18px;
    color: #737380;
    line-height: 32px;;
}

.register-container .content form {
    width: 100%;
    max-width: 450px;
}

.register-container .content form input {
    margin-top: 8px;
}

.register-container .content form .input-group {
    display: flex;
}

.register-container .content form .input-group input + input {
    margin-left: 8px;
}
</style>
