// vue-frontend/src/pages/Account/index.vue
<template>
    <div class="account-container">
        <div class="content">
            <section>
                <img src="../../assets/logo.svg" alt="Be The Hero"/>
                <h1> Conta </h1>
                <p>Atualize as informações de sua ONG ou apague sua conta de nossa aplicação.</p>

                <router-link to="/profile" class="svg-link">
                    <arrow-left-icon size="16" class="red-hero"></arrow-left-icon>
                    Voltar para o perfil
                </router-link>
            </section>
            <form v-on:submit.prevent="handleUpdate">
                <input
                    type="text"
                    placeholder="Nome da ONG"
                    v-model="name"
                    required
                />
                <input 
                    type="email" 
                    placeholder="E-mail" 
                    v-model="email"
                    required
                />
                <input 
                    type="tel" 
                    placeholder="Whatsapp"
                    v-model="whatsapp"
                    required
                    minLength="10"
                    maxLength="11"
                />
                <div class="input-group">
                    <input
                    type="text"
                    placeholder="Cidade" 
                    v-model="city"
                    required
                    style="
                        text-transform: capitalize
                    "
                    />
                    <input
                    type="text"
                    v-model="uf"
                    placeholder="UF"
                    required
                    maxLength="2"
                    style="
                        width: 80px;
                        text-transform: uppercase;
                    "
                    />
                </div>
                <div class="button-group">
                    <button 
                        class="button cancelar"
                        type="button"
                        @click="handleDeleteAccount"
                    >
                        Apagar conta
                    </button>
                    <button :disabled="sending" class="button" type="submit">
                        Atualizar
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>

<script>
import { ArrowLeftIcon } from 'vue-feather-icons'

export default {
    name: 'Account',
    components: {
        ArrowLeftIcon
    },
    data() {
        return {
            sending: false,
            name: '',
            email: '',
            whatsapp: '',
            city: '',
            uf: ''
        }
    },
    mounted() {
        this.axios.get('account')
        .then((response) => {
            this.name = response.data.name
            this.email = response.data.email
            this.whatsapp = response.data.whatsapp
            this.city = response.data.city
            this.uf = response.data.uf
        })
        .catch(() => {
            this.$store.commit('USER_LOGGED', false)
            this.$store.commit('SET_ONG_NAME', null)
            this.$store.commit('SET_EXPIRE_TIME', null)
            localStorage.clear()
            this.$toast.error('Não conseguimos carregar suas informações, faça login novamente.')
            this.$router.push('/')
        })
    },
    methods: {
        async handleDeleteAccount() {
            if (confirm('Tem certeza que quer apagar sua conta?')) {
                await this.axios.delete('ongs')
                .then(() => {
                    this.$store.commit('USER_LOGGED', false)
                    this.$store.commit('SET_ONG_NAME', null)
                    this.$store.commit('SET_EXPIRE_TIME', null)
                    localStorage.clear()
                    this.$router.push({
                        name: 'Login',
                        params: {
                            deleted: true
                        }
                    })
                })
                .catch(() => {
                    this.$toast.error('Não conseguimos apagar sua conta, tente novamente')
                })
            }
        },

        async handleUpdate() {

            this.sending = true

            const name = this.name
            const email = this.email
            const whatsapp = this.whatsapp
            const city = this.city
            const uf = this.uf

            await this.axios.put('account', {
                name,
                email,
                whatsapp,
                city,
                uf
            })
            .then(() => {
                this.$router.push({
                    name: 'Profile',
                    params: {
                        updated: true
                    }
                })
            })
            .catch(() => {
                this.sending = false
                this.$toast.error('Não conseguimos atualizar sua conta, tente novamente')
            })
        }
    }
}
</script>

<style scoped>
.account-container {
    width: 100%;
    max-width: 1120px;
    height: 100vh;
    margin: 0 auto;

    display: flex;
    align-items: center;
    justify-content: center;
}

.account-container .content {
    width: 100%;
    padding: 96px;
    background: #f0f0f5;
    box-shadow: 0 0 100px rgba(0, 0 ,0, 0.1);
    border-radius: 8px;
    
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.account-container .content section {
    width: 100%;
    max-width: 380px;
}

.account-container .content section h1 {
    margin: 64px 0 32px;
    font-size: 32px;
}

.account-container .content section p {
    font-size: 18px;
    color: #737380;
    line-height: 32px;;
}

.account-container .content form {
    width: 100%;
    max-width: 450px;
}

.account-container .content form input {
    margin-top: 8px;
}

.account-container .content form .input-group {
    display: flex;
}

.account-container .content form .input-group input + input {
    margin-left: 8px;
}
.account-container .content form .button-group {
    display: flex;
    justify-content: space-between;
}

.account-container .content form .button-group button + button {
    margin-left: 8px;
}

.account-container .content form .button-group .cancelar {
    width: 60%;
    background: transparent;
    border: 2px solid #2020226b;
    color: rgba(0, 0, 0, 0.884);
    transition: opacity 0.2s;
}

.account-container .content form .button-group .cancelar:hover {
    opacity: 0.8;
}
</style>

// react-frontend/src/pages/Account/index.js
import React, { useState, useRef, useEffect } from "react";
import { Link, useHistory } from "react-router-dom";

// carrega o icone da seta para esquerda do pacote feather icons
import { FiArrowLeft } from "react-icons/fi";

// carrega a api
import api from '../../services/api';

// importa o styles local
import "./styles.css";

// carrega o logo da pasta assets
import logoImg from "../../assets/logo.svg";

export default function Account() {
  
  // instancia o history
  const history = useHistory();

  // define os states
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [whatsapp, setWhatsapp] = useState("");
  const [city, setCity] = useState("");
  const [uf, setUf] = useState("");

  // instancia o btnSave como uma referencia
  const btnSave = useRef();

  // instancia o btnDelete como uma referencia
  const btnDelete = useRef();

  // utiliza o useEffect para carregar uma vez toda vez que for carregada a página ou se o token mudar
  useEffect(() => {
    // faz um pedido GET para a rota do backend 'profile'
    api.get('account')
      .then(response => {
        // define os incidents com o data da resposta
        setName(response.data.name);
        setEmail(response.data.email);
        setWhatsapp(response.data.whatsapp);
        setCity(response.data.city);
        setUf(response.data.uf);
    })
    .catch(err => {
      // se a pessoa não estiver logada
      if(err.response.status === 401) {
        // empurra pra pagina inicial
        history.push('/');
      }
    });
  }, [history]);

  // define a função handleUpdate
  async function handleUpdate(e) {
    // previne o funcionamento normal do envio do formulário
    e.preventDefault();

    // Desabilita o botao para que não seja enviado o formulário mais de uma vez
    btnSave.current.setAttribute('disabled', true);

    // armazena os states dentro da variavel data
    const data = {
      name,
      email,
      whatsapp,
      city,
      uf,
    };

    // bloco de declaração try, se funcionar:
    try {
      // envia os states atualizados com metodo put para a rota 'account' do backend
      const response = await api.put('account', data);

      // atualiza a variavel ongName no localStorage
      localStorage.setItem('ongName', response.data);
      
      // redireciona para o 'profile'
      history.push('/profile', {
        // com state 'updated: true'
        updated: true,
      });

    // se der erro
    } catch (error) {
      // envia alerta de erro ao navegador
      alert('Não conseguimos atualizar suas informações, tente novamente.');
    }
  }

  // define a função handleDeleteAccount
  async function handleDeleteAccount(e) {
    // previne o funcionamento normal do envio do formulário
    e.preventDefault();

    // Desabilita o botao para que não seja enviado o pedido mais de uma vez
    btnDelete.current.setAttribute('disabled', true);

    // bloco de declaração try, se funcionar:
    try {
      // envia metodo delete para a rota 'ongs' do backend
      await api.delete('ongs');

      // apaga todo o localStorage do navegador
      localStorage.clear();

      // redireciona para o 'profile'
      history.push('/', {
        // com state 'deleted: true'
        deleted: true,
      });

    // se der erro
    } catch (error) {
      // envia alerta de erro ao navegador
      alert('Não conseguimos atualizar suas informações, tente novamente.');
    }
  }
  
  // exibe o jsx
  return (
    <div className="register-container">
      <div className="content">
        <section>
          <img src={logoImg} alt="Be The Hero" />
          <h1> Conta </h1> <p>Atualize as informações de sua ONG ou apague sua conta de nossa aplicação.</p>
          <Link to="/profile" className="svg-link">
            <FiArrowLeft size={16} color="#E02041" />
            Voltar para o perfil
          </Link>
        </section>
        <form onSubmit={handleUpdate}>
          <input
            type="text"
            placeholder="Nome da ONG"
            value={name}
            required
            onChange={e => setName(e.target.value)}
          />
          <input 
            type="email" 
            placeholder="E-mail" 
            value={email} 
            required
            onChange={e => setEmail(e.target.value)}
          />
          <input 
            type="tel" 
            placeholder="Whatsapp"
            value={whatsapp} 
            required
            minLength={10}
            maxLength={11}
            onChange={e => setWhatsapp(e.target.value)}
          />
          <div className="input-group">
            <input
              type="text"
              placeholder="Cidade" 
              value={city}
              required
              onChange={e => setCity(e.target.value)}
              style={{
                textTransform: 'capitalize'
              }}
            />
            <input
              type="text"
              value={uf}
              placeholder="UF"
              onChange={e => setUf(e.target.value)}
              required
              maxLength={2}
              style={{
                width: 80,
                textTransform: 'uppercase'
              }}
            />
          </div>
          <div className="button-group">
              <button 
                className="button cancelar"
                type="button"
                ref={btnDelete}
                // emite um alerta(confirm) e chama a função handleDeleteIncident passando o id do incident caso o usuário confirme
                onClick={(e) => { if (window.confirm('Tem certeza que quer apagar sua conta?')) handleDeleteAccount(e) } }
              >
                  Apagar conta
              </button>
              <button ref={btnSave} className="button" type="submit">
                  Atualizar
              </button>
          </div>
        </form>
      </div>
    </div>
  );
}
