// vue-frontend/src/pages/NewIncident/index.vue
<template>
    <div class="new-incident-container">
        <div class="content">
            <section>
                <img src="../../assets/logo.svg" alt="Be The Hero"/>
                <h1>Cadastrar novo caso</h1>
                <p>
                    Descreva o caso detalhadamente para encontrar um herói para resolver isso.
                </p>

                <router-link to="/profile" class="svg-link">
                    <arrow-left-icon size="16" class="red-hero"></arrow-left-icon>
                    Voltar para o perfil
                </router-link>
            </section>
            <form 
                ref="new_incident"
                v-on:submit.prevent="handleNewIncident"
            >
                <input 
                    placeholder="Título do caso"
                    v-model="title"
                    required
                />
                <textarea 
                    placeholder="Descrição"
                    v-model="description"
                    required
                />
                <input 
                    type="number" 
                    placeholder="Valor em reais"
                    v-model="value"
                    required
                />
                <div class="button-group">
                    <button class="button cancelar" type="button" @click="$refs.new_incident.reset()">
                        Limpar
                    </button>
                    <button :disabled="sending" class="button" type="submit">
                        Cadastrar
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>


<script>
import { ArrowLeftIcon } from 'vue-feather-icons'

export default {
    name: 'NewIncident',
    components: {
        ArrowLeftIcon
    },
    data() {
        return {
            title: '',
            description: '',
            value: '',
            sending: false,

        }
    },
    methods: {
        async handleNewIncident() {
            this.sending = true
            
            const title = this.title
            const description = this.description
            const value = this.value

            await this.axios.post('incidents', { title, description, value })
            .then(() => {
                this.$toast.success('Novo caso adicionado.')
                this.$router.push('/profile')
            })
            .catch(() => {
                this.sending = false
                this.$toast.error('Não conseguimos adicionar o novo caso, tente novamente')
            })
        }
    },
}
</script>


<style scoped>
.new-incident-container {
    width: 100%;
    max-width: 1120px;
    height: 100vh;
    margin: 0 auto;

    display: flex;
    align-items: center;
    justify-content: center;
}

.new-incident-container .content {
    width: 100%;
    padding: 96px;
    background: #f0f0f5;
    box-shadow: 0 0 100px rgba(0, 0 ,0, 0.1);
    border-radius: 8px;
    
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.new-incident-container .content section {
    width: 100%;
    max-width: 380px;
}

.new-incident-container .content section h1 {
    margin: 64px 0 32px;
    font-size: 32px;
}

.new-incident-container .content section p {
    font-size: 18px;
    color: #737380;
    line-height: 32px;;
}

.new-incident-container .content form {
    width: 100%;
    max-width: 450px;
}

.new-incident-container .content form input,
.new-incident-container .content form textarea {
    margin-top: 8px;
}

.new-incident-container .content form .button-group {
    display: flex;
    justify-content: space-between;
}

.new-incident-container .content form .button-group button + button {
    margin-left: 8px;
}

.new-incident-container .content form .button-group .cancelar {
    width: 60%;
    background: transparent;
    border: 2px solid #2020226b;
    color: rgba(0, 0, 0, 0.884);
    transition: opacity 0.2s;
}

.new-incident-container .content form .button-group .cancelar:hover {
    opacity: 0.8;
}
</style>

// react-frontend/src/pages/NewIncident/index.js
import React, { useState, useRef } from 'react';
import { Link, useHistory } from 'react-router-dom';

// carrega o icone da seta para esquerda do pacote feather icons
import { FiArrowLeft } from 'react-icons/fi';

// carrega a api
import api from '../../services/api';

// importa o styles local
import './styles.css';

// carrega o logo da pasta assets
import logoImg from '../../assets/logo.svg';

export default function NewIncident() {

    // instancia o history
    const history = useHistory();

    // define os states
    const [title, setTitle] = useState("");
    const [description, setDescription] = useState("");
    const [value, setValue] = useState("");

    // instancia o btnRegister como uma referencia
    const btnRegister = useRef();

    // verifica se existe o ongname no localstorage senao envia para pagina inicial
    const ongName = localStorage.getItem('ongName');
    if(!ongName) {
        history.push('/');
    }

    // define a função handleNewIncident
    async function handleNewIncident(e) {
        // previne o funcionamento normal do envio do formulário
        e.preventDefault();

        // Desabilita o botao para que não seja enviado o formulário mais de uma vez
        btnRegister.current.setAttribute('disabled', true);

        // armazena o title, description, value dentro da variavel data
        const data = {
            title,
            description,
            value,
        };

        // bloco de declaração try, se funcionar:
        try {
            // envia os dados do formulário como metodo post para a rota 'incidents' do backend
            await api.post('incidents', data)
            .catch(err => {
                // se a pessoa não estiver logada
                if(err.response.status === 401) {
                    // empurra pra pagina inicial
                    history.push('/');
                }
              });
            // direciona para página profile
            history.push('/profile');

        // se der erro
        } catch (error) {
            // libera o uso do botão novamente
            btnRegister.current.removeAttribute('disabled');
            // envia alerta de erro ao navegador
            alert('Erro ao cadastrar caso, tente novamente.');
        }
    }

    // imprime o jsx
    return (
        <div className="new-incident-container">
            <div className="content">
                <section>
                    <img src={logoImg} alt="Be The Hero"/>
                    <h1>Cadastrar novo caso</h1>
                    <p>
                        Descreva o caso detalhadamente para encontrar um herói para resolver isso.
                    </p>

                    <Link to="/profile" className="svg-link">
                        <FiArrowLeft size={16} color="#E02041" />
                        Voltar para o perfil
                    </Link>
                </section>
                <form 
                    id="new-incident"
                    onSubmit={handleNewIncident}
                >
                    <input 
                        placeholder="Título do caso"
                        value={title}
                        required
                        onChange={e => setTitle(e.target.value)}
                    />
                    <textarea 
                        placeholder="Descrição"
                        value={description}
                        required
                        onChange={e => setDescription(e.target.value)}
                    />
                    <input 
                        type="number" 
                        placeholder="Valor em reais"
                        value={value}
                        required
                        onChange={e => setValue(e.target.value)}
                    />
                    <div className="button-group">
                        <button className="button cancelar" type="button" onClick={() => {
                            document.getElementById("new-incident").reset()
                        }}>
                            Limpar
                        </button>
                        <button ref={btnRegister} className="button" type="submit">
                            Cadastrar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
}
