// react-frontend/src/pages/Profile/index.js
import React, { useState, useEffect } from 'react';
import { Link, useHistory } from 'react-router-dom';

// carrega o icone da Power e o trash2 do pacote feather icons
import { FiPower, FiEdit, FiTrash2, FiSettings } from 'react-icons/fi';

// carrega a api
import api from '../../services/api';

// importa o styles local
import './styles.css';

// carrega o logo da pasta assets
import logoImg from '../../assets/logo.svg';

export default function Profile() {

    // instancia o history
    const history = useHistory();

    // define os states
    const [incidents, setIncidents] = useState([]);
    const [total, setTotal] = useState(0);
    const [page, setPage] = useState(1);
    const [loading, setLoading] = useState(false);
    const [updateAlert, setShowUpdateAlert] = useState(false);

    // get ongName
    localStorage.getItem('ongName');

    // define a função loadIncidents
    async function loadIncidents() {
        // se já tiver carregando mais incidents
        if(loading) {
            // retorne e não faça nada
            return;
        }
        
        // se o total de incidents for maior que 0 e o numero de incidents listados for igual ao total
        if (total > 0 && incidents.length === total) {
            // retorne e não faça nada
            return;
        }

        // define loading verdadeiro
        setLoading(true);

        // solicita com metodo get para a rota 'profile' do backend
        const response = await api.get('profile', {
            // define um params no pedido get chamado page com o valor da pagina atual
            params: { page }
        });

        // concatena(junta) os incidents atuais da lista junto com os incidents enviados pelo backend no data da resposta
        setIncidents([...incidents, ...response.data]);

        // pega o total de incidents do cabeçalho da resposta
        setTotal(response.headers['x-total-count']);
        
        // soma 1 a pagina atual
        setPage(page+1);

        // define loading falso
        setLoading(false);
    
    }
    
    let showUpdatedAlert = false;

    if (history.location.state && history.location.state.updated) {
        showUpdatedAlert = true;
    } else {
        showUpdatedAlert = false;
    }

    // utiliza o useEffect para carregar uma vez toda vez que for carregada a página ou se o ongKey mudar
    useEffect(() => {

        // pega quando o cookie expira
        const expire = localStorage.getItem('expire_at');
        // agora
        const now = new Date();
        // diferença entre as datas
        const milliseconds = Math.abs(now - expire);
        // qnts horas faltam
        const hours = milliseconds / 36e5;
        
        // se faltar 1 hr para vencer o cookie atualiza
        if (hours > 0 && hours < 1) {
            api.put('sessions')
            .then(response => {
                localStorage.setItem('ongName', response.name);
            });
        }

        // é para mostrar o updatealert?
        if (showUpdatedAlert) {
            // mostre o updatealert
            setShowUpdateAlert(true);
        }
        // faz um pedido GET para a rota do backend 'profile'
        api.get('profile', {
            // se tiver uma resposta
        }).then(response => {
            // define os incidents com o data da resposta
            setIncidents(response.data);
            // define o total tirando do cabeçalho da resposta o x-total-count
            setTotal(response.headers['x-total-count']);
            // carrega a primeira pagina e já coloca a segunda
            setPage(2);
        })
        .catch(err => {
            if(err.response.statusCode === 401) {
                // falhou login
                localStorage.setItem('expired', true);
                // vai pro login
                history.push('/');
            }
        });
    }, [showUpdatedAlert, history]);

    // define a função handleDeleteIncident
    async function handleDeleteIncident(id) {
        // bloco de declaração try, se funcionar:
        try {
            // envia como metodo delete para a rota 'incidents/:id' do backend com o id passado a função handleDeleteIncident
            await api.delete(`/incidents/${id}`);
            // filtra e remove dos incidents o incident que tiver o mesmo id do incident apagado
            setIncidents(incidents.filter(incident => incident.id !== id));

        // se der erro
        } catch (error) {
            // envia alerta de erro ao navegador
            alert('Erro ao deletar o caso, tente novamente.');
        }
    }

    function handleEditIncident(incident) {
        history.push('/incidents', {
            id: incident.id
        });
    }

    // define a função handleLogout
    async function handleLogout() {
        
        // deleta a sessao e seta o cookie nulo
        await api.delete('sessions')
        .catch(error => {
            alert(error.response.data.error);
        });
        
        // foi feito pedido de logout
        localStorage.clear();

        // empurra o cliente para a tela inicial
        history.push('/');
    }

    // exibe o jsx abaixo
    return (
        <div className="profile-container">
            <header>
                <img src={logoImg} alt="Be The Hero"/>
                <span>Bem vinda, {localStorage.getItem('ongName')}</span>

                <Link className="button" to="/incidents/new">
                    Cadastrar novo caso
                </Link>
                <button onClick={() => history.push('/account')} type="button">
                    <FiSettings size={18} color="#E02041" />
                </button>
                <button type="button" onClick={handleLogout}>
                    <FiPower size={18} color="#E02041" />
                </button>
            </header>

            {(updateAlert ?
                <div className="confirmUpdate">
                    Sua conta foi atualizada com sucesso.
                </div>
            :
                ''
            )}

            <h1>Casos cadastrados</h1>

            {
            // o numero de incidents é maior que 0 ?
            (incidents.length > 0 ? // se sim exiba o jsx abaixo
                    <div>
                        <ul>
                            {
                            // faz um loop exibindo todos os 'incident' dentro da lista 'incidents'
                            incidents.map(incident => (
                                <li key={incident.id}>
                                    <span className="caso-titulo">Caso:</span>
                                    <p>{incident.title}</p>

                                    <span className="caso-titulo">Descrição</span>
                                    <p>{incident.description}</p>

                                    <span className="caso-titulo">Valor:</span>
                                    <p>{incident.value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</p>
                                    <button 
                                        type="button"
                                        // emite um alerta(confirm) e chama a função handleDeleteIncident passando o id do incident caso o usuário confirme
                                        onClick={() => handleEditIncident(incident)}
                                        style={{
                                            right: 60
                                        }}
                                    >
                                        <FiEdit size={20} color="#a8a8b3" />
                                    </button>
                                    <button 
                                        type="button"
                                        // emite um alerta(confirm) e chama a função handleDeleteIncident passando o id do incident caso o usuário confirme
                                        onClick={(e) => { if (window.confirm('Tem certeza que quer apagar este caso?')) handleDeleteIncident(incident.id) }}
                                    >
                                        <FiTrash2 size={20} color="#a8a8b3" />
                                    </button>
                                </li>
                            ))}
                        </ul>
                        {
                        // o total de incidents é maior que 0 e o numero de incidents exibidos é menor que o total ?
                        (total > 0 && incidents.length + 1 < total) ? // se sim mostre o jsx abaixo
                            <div className="align-center">
                                <button
                                type="button"
                                className="button"
                                // chama a função loadIncidents para carregar mais incidents
                                onClick={loadIncidents}
                                >
                                    Carregar mais
                                </button>
                            </div>
                        : // senão não mostre nada
                            ''
                        }
                    </div>
                :  // senão mostre a mensagem abaixo
                <p>Ainda não há casos a serem exibidos.</p>
            )}
            
        </div>
    );
}

// vue-frontend/src/pages/Profile/index.vue
<template>
    <div class="profile-container">
            <header>
                <img src="../../assets/logo.svg" alt="Be The Hero"/>
                <span>Bem vinda, {{ ongName }}</span>

                <router-link class="button" to="/incidents/new">
                    Cadastrar novo caso
                </router-link>
                <button @click="$router.push('/account')" type="button">
                    <settings-icon size="18" class="red-hero"></settings-icon>
                </button>
                <button type="button" @click="handleLogout">
                    <power-icon size="18" class="red-hero"></power-icon>
                </button>
            </header>

            <div v-show="updateAlert" class="confirmUpdate">
                Sua conta foi atualizada com sucesso.
            </div>

            <h1>Casos cadastrados</h1>

            <div v-if="incidents.length > 0">
                <ul>
                    <li v-for="incident in incidents" v-bind:key="incident.id">
                        <span class="caso-titulo">Caso:</span>
                        <p>{{ incident.title }}</p>

                        <span class="caso-titulo">Descrição</span>
                        <p>{{ incident.description }}</p>

                        <span class="caso-titulo">Valor:</span>
                        <p>{{ incident.value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) }}</p>
                        <button 
                            type="button"
                            @click="handleEditIncident(incident)"
                            style="right: 60px"
                        >
                            <edit-icon size="20" class="gray-hero"></edit-icon>
                        </button>
                        <button 
                            type="button"
                            @click="handleDeleteIncident(incident.id)"
                        >
                            <trash-2-icon size="20" class="gray-hero"></trash-2-icon>
                        </button>
                    </li>
                </ul>
                <div v-if="total > 0 && incidents.length + 1 < total" class="align-center">
                    <button
                    type="button"
                    class="button"
                    @click="loadIncidents"
                    >
                        Carregar mais
                    </button>
                </div>
            </div>
            <p v-else>Ainda não há casos a serem exibidos.</p>
        </div>
</template>

<script>
import { Trash2Icon, EditIcon, PowerIcon, SettingsIcon } from 'vue-feather-icons'

import { mapState } from 'vuex'

export default {
    name: 'Profile',
    components: {
        Trash2Icon, EditIcon, PowerIcon, SettingsIcon
    },
    data() {
        return {
            loading: false,
            total: 0,
            incidents: [],
            updateAlert: false,
        }
    },
    mounted() {
        if (this.$route.params.updated === true) {
            this.updateAlert = true
        }

        // pega quando o cookie expira
        const expire = localStorage.getItem('expire_at')
        // agora
        const now = new Date()
        // diferença entre as datas
        const milliseconds = Math.abs(now - expire)
        // qnts horas faltam
        const hours = milliseconds / 36e5
        
        // se faltar 1 hr para vencer o cookie atualiza
        if (hours > 0 && hours < 1) {
            this.axios.put('sessions')
            .then((response) => {
                this.$store.commit('SET_ONG_NAME', response.data.name)
            })
        }

        this.loadIncidents()
    },
    methods: {
        async loadIncidents() {
            // se já tiver carregando mais incidents
            if(this.loading) {
                // retorne e não faça nada
                return;
            }
            
            // se o total de incidents for maior que 0 e o numero de incidents listados for igual ao total
            if (this.total > 0 && this.incidents.length === this.total) {
                // retorne e não faça nada
                return;
            }

            // define loading verdadeiro
            this.loading = true

            // solicita com metodo get para a rota 'profile' do backend
            const page = this.page
            
            await this.axios.get('profile', {
                // define um params no pedido get chamado page com o valor da pagina atual
                params: { page }
            })
            .then((response) => {
                // concatena(junta) os incidents atuais da lista junto com os incidents enviados pelo backend no data da resposta
                let incidents = this.incidents
    
                incidents = [...incidents, ...response.data]
    
                this.incidents = incidents
    
                // pega o total de incidents do cabeçalho da resposta
                this.total = response.headers['x-total-count']
                
                // soma 1 a pagina atual
                this.page = this.page + 1
    
                // define loading falso
                this.loading = false
            })
            .catch(() => {
                this.$store.commit('USER_LOGGED', false)
                this.$store.commit('SET_ONG_NAME', null)
                this.$store.commit('SET_EXPIRE_TIME', null)
                localStorage.clear()
                this.$toast.error('Não conseguimos carregar seus casos, faça login novamente.')
                this.$router.push('/')
            });
        },

        handleEditIncident(incident) {
            this.$router.push(
                {
                    name: 'IncidentEdit',
                    params: {
                        id: incident.id
                    }
                }
            )
        },

        async handleDeleteIncident(id) {
            if (confirm('Tem certeza que quer apagar este caso?')) {
                await this.axios.delete(`incidents/${id}`)
                .then(() => {
                    this.$toast.success('Caso apagado.')
                    this.incidents = this.incidents.filter(incident => incident.id !== id)
                })
                .catch(() => {
                    this.$toast.error('Não conseguimos apagar este caso, tente novamente.')
                })
            }
        },
        
        async handleLogout() {
            // foi feito pedido de logout
            this.$store.commit('USER_LOGGED', false)

            // deleta a sessao e seta o cookie nulo
            await this.axios.delete('sessions')
            .then(() => {
                localStorage.clear()
            })
            
            // empurra o cliente para a tela inicial
            this.$router.push('/');
        },
    },
    computed: {
        ...mapState([
            'ongName'
        ])
    },
}
</script>

<style scoped>
.profile-container {
    width: 100%;
    max-width: 1180px;
    padding: 0 30px;
    margin: 32px auto;
}

.profile-container header {
    display: flex;
    align-items: center;
}

.profile-container header span {
    font-size: 20px;
    margin-left: 24px;
}

.profile-container header img {
    height: 64px;
}

.profile-container header a {
    width: 260px;
    margin-left: auto;
    margin-top: 0;
}

.profile-container header button {
    height: 60px;
    width: 60px;
    border-radius: 4px;
    border: 1px solid #dcdce6;
    background: transparent;
    margin-left: 16px;
    transition: border-color 0.2s;
}

.profile-container header button:hover {
    border-color: #999;
}

.profile-container header span span {
    background: #fff;
    padding: 5px 15px;
    font-size: 11px;
    border-radius: 8px;
}

.profile-container h1 {
    margin-top: 80px;
    margin-bottom: 24px;
}

.profile-container ul {
    display: grid;
    grid-template-columns: 1fr 1fr;
    grid-gap: 24px;
    list-style: none;
}

.profile-container ul li {
    background: #fff;
    padding: 24px;
    border-radius: 8px;
    position: relative;
}

.profile-container ul li button {
    position: absolute;
    right: 24px;
    top: 24px;
    border: 0;
    background: transparent;
    transition: opacity 0.2s;
}

.profile-container ul li button:hover {
    opacity: 0.8;
}

.profile-container ul li .caso-titulo {
    font-weight: 700;
    text-transform: uppercase;
    display: block;
    margin-bottom: 16px;
    color: #41414d;
}

.profile-container ul li p + .caso-titulo {
    margin-top: 32px;
}

.profile-container ul li p {
    color: #737380;
    line-height: 21px;
    font-size: 16px;
}

.profile-container .confirmUpdate {
    margin-top: 65px;
    text-align: center;
    padding: 20px;
    background: #bcf8d7;
    color: #019141;
    border: 1px solid #019141;
    border-radius: 8px;
}
</style>
